spring.application.name=chess-opening-trainer-backend

server.port=${PORT:8080}

cors.allowed.origins=${ALLOWED_ORIGINS:http://localhost:3000}

logging.level.root=INFO
logging.level.com.ogmikee.chess=DEBUG